# devices.yml - Device definitions
# Network Toolkit Device Configuration

devices:
  nw-hapac-md-desk1:
    host: "192.168.88.2"
    device_type: "mikrotik_routeros"
    platform: "arm"
    model: "HAPAC2"

  nw-hapac-md-desk1-netmiko:
    host: "192.168.88.2"
    device_type: "mikrotik_routeros"
    platform: "arm"
    model: "HAPAC2"
    description: "HAPAC2 - Netmiko Connection"
    transport_type: "nornir_netmiko"

    # Netmiko-specific configuration
    netmiko:
      device_type: "mikrotik_routeros"
      host: "192.168.88.2"
      port: 22
      timeout: 30
      auth_timeout: 10
      banner_timeout: 15

   # Access Layer Switches
  sw-acc1:
    host: "10.10.1.11"
    description: "Access Switch 1 - Floor 1 East Wing"
    device_type: "mikrotik_routeros"
    platform: "mipbsbe"
    model: "CRS326-24G-2S+"
    location: "Floor 1 East IDF"

    # Tagging for group membership and filtering
    tags:
      - "switch"
      - "access"
      - "floor1"
      - "critical"
      - "managed"

    # Device-specific connection overrides (optional)
    connection:
      timeout: 45
      command_timeout: 90

    # Custom attributes for documentation/automation
    attributes:
      vlan_range: "100-199"
      uplink_ports: ["sfp-sfpplus1", "sfp-sfpplus2"]
      management_vlan: 99

  sw-acc1-netmiko:
    host: "10.10.1.11"
    device_type: "mikrotik_routeros"
    platform: "mipbsbe"
    model: "CRS326-24G-2S+"
    description: "Access Switch 1 - Netmiko Connection"
    transport_type: "nornir_netmiko"

    # Netmiko-specific configuration
    netmiko:
      device_type: "mikrotik_routeros"
      host: "10.10.1.11"
      port: 22
      timeout: 45
      auth_timeout: 15
      banner_timeout: 20

  sw-acc2:
    host: "10.10.1.12"
    description: "Access Switch 2 - Floor 1 West Wing"
    device_type: "mikrotik_routeros"
    platform: "mipbsbe"
    model: "CRS326-24G-2S+"
    location: "Floor 1 West IDF"

    tags:
      - "switch"
      - "access"
      - "floor1"
      - "critical"
      - "managed"

    attributes:
      vlan_range: "200-299"
      uplink_ports: ["sfp-sfpplus1", "sfp-sfpplus2"]
      management_vlan: 99

  sw-acc2-netmiko:
    host: "10.10.1.12"
    device_type: "mikrotik_routeros"
    platform: "mipbsbe"
    model: "CRS326-24G-2S+"
    description: "Access Switch 2 - Netmiko Connection"
    transport_type: "nornir_netmiko"

    # Netmiko-specific configuration
    netmiko:
      device_type: "mikrotik_routeros"
      host: "10.10.1.12"
      port: 22
      timeout: 30
      auth_timeout: 10
      banner_timeout: 15

  # Distribution Layer
  sw-dist1:
    host: "10.10.1.13"
    description: "Distribution Switch 1 - Core Network"
    device_type: "mikrotik_routeros"
    platform: "mipbsbe"
    model: "CRS317-1G-16S+"
    location: "Main Server Room"

    tags:
      - "switch"
      - "distribution"
      - "core"
      - "critical"
      - "high-performance"
      - "managed"

    # Higher timeouts for complex operations
    connection:
      timeout: 60
      command_timeout: 120

    attributes:
      role: "aggregation"
      uplink_speed: "10G"
      redundancy: "dual-homed"

  sw-dist1-netmiko:
    host: "10.10.1.13"
    device_type: "mikrotik_routeros"
    platform: "mipbsbe"
    model: "CRS317-1G-16S+"
    description: "Distribution Switch 1 - Netmiko Connection"
    transport_type: "nornir_netmiko"

    # Netmiko-specific configuration
    netmiko:
      device_type: "mikrotik_routeros"
      host: "10.10.1.13"
      port: 22
      timeout: 60
      auth_timeout: 20
      banner_timeout: 25

  # Edge Router
  rtr-edge1:
    host: "10.10.1.1"
    description: "Edge Router - Internet Gateway"
    device_type: "mikrotik_routeros"
    platform: "mipbsbe"
    model: "RB5009UG+S+"
    location: "Main Server Room"

    tags:
      - "router"
      - "edge"
      - "internet"
      - "critical"
      - "firewall"
      - "managed"

    connection:
      timeout: 60
      command_timeout: 180  # Longer for routing operations

    attributes:
      wan_interfaces: ["ether1"]
      lan_interfaces: ["ether2", "ether3", "ether4", "ether5"]
      wifi_capable: true
      vpn_server: true

  # Example of device with custom credentials (via env vars)
  # Credentials would be: NT_SW_GUEST_USER, NT_SW_GUEST_PASSWORD
  sw-guest:
    host: "10.10.1.20"
    description: "Guest Network Switch"
    device_type: "mikrotik_routeros"
    platform: "mipbsbe"
    model: "CRS309-1G-8S+"
    location: "Reception Area"

    tags:
      - "switch"
      - "guest"
      - "isolated"
      - "non-critical"
      - "managed"

    attributes:
      network_segment: "guest"
      isolation_enabled: true
      internet_only: true

  # Example wireless device
  ap-lobby1:
    host: "10.10.1.50"
    description: "Wireless Access Point - Main Lobby"
    device_type: "mikrotik_routeros"
    platform: "arm"
    model: "cAP ac"
    location: "Main Lobby Ceiling"

    tags:
      - "wireless"
      - "access-point"
      - "public"
      - "managed"

    attributes:
      wireless_bands: ["2.4GHz", "5GHz"]
      max_clients: 100
      coverage_area: "lobby"

  # Multi-vendor examples below

  # Cisco IOS-XE Switch
  sw-core-cisco1:
    host: "10.10.1.100"
    description: "Cisco Core Switch - Data Center"
    device_type: "cisco_iosxe"
    platform: "cisco_iosxe"
    model: "Catalyst 9300"
    location: "Data Center Rack A1"

    tags:
      - "switch"
      - "core"
      - "cisco"
      - "critical"
      - "managed"

    attributes:
      role: "core"
      stack_members: 2
      uplink_speed: "40G"

  # Cisco NX-OS Switch
  sw-dc-nexus1:
    host: "10.10.1.101"
    description: "Cisco Nexus Data Center Switch"
    device_type: "cisco_nxos"
    platform: "cisco_nxos"
    model: "Nexus 9000"
    location: "Data Center Rack B1"

    tags:
      - "switch"
      - "datacenter"
      - "cisco"
      - "critical"
      - "managed"

    attributes:
      role: "leaf"
      vpc_enabled: true
      fabric_role: "spine"

  # Arista EOS Switch
  sw-spine-arista1:
    host: "10.10.1.102"
    description: "Arista Spine Switch"
    device_type: "arista_eos"
    platform: "arista_eos"
    model: "DCS-7280SR"
    location: "Data Center Spine"

    tags:
      - "switch"
      - "spine"
      - "arista"
      - "critical"
      - "managed"

    attributes:
      role: "spine"
      bgp_asn: 65001
      mlag_enabled: true

  # Juniper JunOS Switch
  sw-campus-juniper1:
    host: "10.10.1.103"
    description: "Juniper Campus Switch"
    device_type: "juniper_junos"
    platform: "juniper_junos"
    model: "EX4300"
    location: "Campus Building A"

    tags:
      - "switch"
      - "campus"
      - "juniper"
      - "managed"

    attributes:
      role: "access"
      virtual_chassis: true
      poe_enabled: true
