# groups.yml - Device group definitions
# Network Toolkit Device Groups Configuration

groups:
  # Infrastructure-based groups
  all_switches:
    description: "All network switches in the infrastructure"
    match_tags:
      - "switch"
    members: []  # Auto-populated from tag matching

  access_switches:
    description: "Access layer switches"
    match_tags:
      - "switch"
      - "access"

  clab_simple_all3_devices:
    description: "All 3 switches"
    members:
      - "sw-acc1"
      - "sw-acc2"
      - "sw-dist1"

  distribution_switches:
    description: "Distribution layer switches"
    match_tags:
      - "switch"
      - "distribution"

  all_routers:
    description: "All routers in the network"
    match_tags:
      - "router"

  wireless_devices:
    description: "All wireless access points and controllers"
    match_tags:
      - "wireless"

  # Criticality-based groups
  critical_infrastructure:
    description: "Mission-critical network devices"
    match_tags:
      - "critical"
    priority: "high"

  non_critical:
    description: "Non-critical devices (guest, IoT, etc.)"
    match_tags:
      - "non-critical"
    priority: "low"

  # Location-based groups
  floor1_devices:
    description: "All devices on Floor 1"
    match_tags:
      - "floor1"

  server_room:
    description: "Devices located in the main server room"
    members:
      - "sw-dist1"
      - "rtr-edge1"

  # Function-based groups
  edge_devices:
    description: "Edge network devices (internet-facing)"
    match_tags:
      - "edge"
      - "internet"

  core_network:
    description: "Core network infrastructure"
    match_tags:
      - "core"
      - "distribution"

  managed_devices:
    description: "All centrally managed devices"
    match_tags:
      - "managed"

  # IBB customer specific groups
  ibb_all:
    description: "All IBB customer devices"
    match_tags:
      - "customer:ibb"

  ibb_site_br:
    description: "IBB devices at site BR"
    members:
      - ibb-ot-core1-br
      - ibb-ot-core2-br
      - ibb-ot-vpn1-br
      - ibb-ot-lwl1-br

  ibb_site_lu:
    description: "IBB devices at site LU"
    members:
      - ibb-ot-core1-lu
      - ibb-ot-core2-lu
      - ibb-ot-vpn1-lu
      - ibb-ot-lwl1-lu

  ibb_core:
    description: "IBB core devices"
    members:
      - ibb-ot-core1-br
      - ibb-ot-core2-br
      - ibb-ot-core1-lu
      - ibb-ot-core2-lu

  ibb_vpn:
    description: "IBB VPN devices"
    members:
      - ibb-ot-vpn1-br
      - ibb-ot-vpn1-lu

  ibb_lwl:
    description: "IBB LWL devices"
    members:
      - ibb-ot-lwl1-br
      - ibb-ot-lwl1-lu

  ibb_wireless:
    description: "IBB wireless devices"
    members:
      - ibb-ot-sxt

  ibb_edge:
    description: "IBB edge devices"
    members:
      - ibb-ot-hexs

  ibb_firewall:
    description: "IBB firewall devices"
    members:
      - ibb-ot-fw

  # Special purpose groups
  firmware_update_batch1:
    description: "First batch for firmware updates (non-critical)"
    members:
      - "sw-guest"
      - "ap-lobby1"
    update_schedule: "maintenance_window_1"

  firmware_update_batch2:
    description: "Second batch for firmware updates (access layer)"
    members:
      - "sw-acc1"
      - "sw-acc2"
    update_schedule: "maintenance_window_2"

  firmware_update_batch3:
    description: "Final batch for firmware updates (critical core)"
    members:
      - "sw-dist1"
      - "rtr-edge1"
    update_schedule: "maintenance_window_3"

  # Operational groups
  backup_daily:
    description: "Devices with daily backup requirements"
    match_tags:
      - "critical"
    backup_schedule: "daily"

  backup_weekly:
    description: "Devices with weekly backup requirements"
    match_tags:
      - "non-critical"
    backup_schedule: "weekly"

  # Network segments
  production_network:
    description: "Production network devices"
    match_tags:
      - "production"
    exclude_tags:
      - "guest"
      - "isolated"

  guest_network:
    description: "Guest network infrastructure"
    match_tags:
      - "guest"
      - "isolated"

# Group inheritance and relationships
group_relationships:
  # Groups can inherit properties from parent groups
  access_switches:
    inherits_from: "all_switches"

  distribution_switches:
    inherits_from: "all_switches"

  # Groups can have dependencies (for ordered operations)
  dependencies:
    access_switches:
      depends_on: "distribution_switches"
    distribution_switches:
      depends_on: "core_network"

# Default group behaviors
defaults:
  # How to handle device membership conflicts
  conflict_resolution: "most_specific"  # most_specific, first_match, all_groups

  # Default execution order for group operations
  execution_order: "dependency_first"  # dependency_first, alphabetical, parallel

  # Default error handling for group operations
  error_handling: "continue"  # continue, stop_on_first_error, stop_on_critical_error

# Additional vendor and multi-vendor groups
vendor_groups:
  # Vendor-based groups
  mikrotik_devices:
    description: "All MikroTik devices"
    match_tags:
      - "mikrotik"

  cisco_devices:
    description: "All Cisco devices (IOS-XE and NX-OS)"
    match_tags:
      - "cisco"

  arista_devices:
    description: "All Arista EOS devices"
    match_tags:
      - "arista"

  juniper_devices:
    description: "All Juniper JunOS devices"
    match_tags:
      - "juniper"

  # Multi-vendor device type groups
  all_core_switches:
    description: "Core switches from all vendors"
    match_tags:
      - "core"

  all_spine_switches:
    description: "Spine switches from all vendors"
    match_tags:
      - "spine"

  datacenter_switches:
    description: "Data center switches from all vendors"
    match_tags:
      - "datacenter"
      - "core"
      - "spine"
