# sequences.yml - Multi-vendor command sequences configuration
# Network Toolkit Multi-Vendor Command Sequences Configuration

# Multi-vendor sequence support
# Sequences are now organized by vendor platform following Scrapli naming conventions:
# - mikrotik_routeros/
# - cisco_iosxe/
# - cisco_nxos/
# - arista_eos/
# - juniper_junos/
#
# The system automatically selects the appropriate vendor sequences based on the
# device_type defined in devices.yml

# Vendor platform mappings
vendor_platforms:
  mikrotik_routeros:
    description: "MikroTik RouterOS devices"
    sequence_path: "sequences/mikrotik_routeros"
    default_files: ["common.yml"]

  cisco_iosxe:
    description: "Cisco IOS-XE devices"
    sequence_path: "sequences/cisco_iosxe"
    default_files: ["common.yml"]

  cisco_nxos:
    description: "Cisco NX-OS devices"
    sequence_path: "sequences/cisco_nxos"
    default_files: ["common.yml"]

  arista_eos:
    description: "Arista EOS devices"
    sequence_path: "sequences/arista_eos"
    default_files: ["common.yml"]

  juniper_junos:
    description: "Juniper JunOS devices"
    sequence_path: "sequences/juniper_junos"
    default_files: ["common.yml"]

# Legacy sequences (for backward compatibility)
# These are now deprecated in favor of vendor-specific sequences
# Will be removed in a future version
sequences: {}

# Sequence execution policies
policies:
  # Default behavior for sequence execution
  default_execution:
    continue_on_error: true
    max_failures: 3
    retry_failed_commands: false

  # Critical sequence execution (stricter)
  critical_execution:
    continue_on_error: false
    max_failures: 1
    retry_failed_commands: true
    retry_count: 2

  # Monitoring sequence execution (more lenient)
  monitoring_execution:
    continue_on_error: true
    max_failures: 5
    retry_failed_commands: false
    timeout_multiplier: 1.5

# Sequence categories for organization
categories:
  information:
    description: "Information gathering sequences"
    default_policy: "default_execution"

  monitoring:
    description: "Device monitoring and health checks"
    default_policy: "monitoring_execution"

  network:
    description: "Network configuration and status"
    default_policy: "default_execution"

  security:
    description: "Security auditing and access control"
    default_policy: "critical_execution"

  maintenance:
    description: "Device maintenance and backup operations"
    default_policy: "critical_execution"

  troubleshooting:
    description: "Diagnostic and troubleshooting sequences"
    default_policy: "default_execution"

  wireless:
    description: "Wireless-specific operations"
    default_policy: "default_execution"

  device-specific:
    description: "Device type specific sequences"
    default_policy: "default_execution"
