name: Test GitHub Installation

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - '.github/workflows/test-publish.yml'
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: "1"

jobs:
  test-git-install:
    name: Test GitHub installation methods
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Test direct Git installation
      run: |
        python -m pip install --upgrade pip
        python -m pip install git+https://github.com/narrowin/net-worker.git@${{ github.sha }}

    - name: Test installed package
      run: |
        nw --help
        python -c "import network_toolkit; print('✅ Import successful')"
        nw --version || echo "Version command not available"

    - name: Uninstall for next test
      run: python -m pip uninstall -y net-worker

  test-local-build-install:
    name: Test local build and install
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install 3.12

    - name: Build package
      run: uv build

    - name: Test wheel installation
      run: |
        python -m pip install --upgrade pip
        python -m pip install dist/*.whl

    - name: Test installed package
      run: |
        nw --help
        python -c "import network_toolkit; print('✅ Wheel installation successful')"

    - name: Test source distribution installation
      run: |
        python -m pip uninstall -y net-worker
        python -m pip install dist/*.tar.gz

    - name: Test source installation
      run: |
        nw --help
        python -c "import network_toolkit; print('✅ Source distribution installation successful')"
